#!/usr/bin/env bash
# This script displays the first 100 number
# For numbers divisible by 3 and 5, it displays "FizzBuzz"
# For numbers divisible by 3, it displays "Fizz" 
# For numbers divisible by 5, it displays "Buzz"
# If not show number

for i in {1..100}
do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done