#!/usr/bin/env bash
# This script displays "Best School" 10 times
# At the 4th and 8th count, it will display "bad luck" and "good luck" instead.

counter=1
while [ $counter -le 10 ]
do
    if [[ $counter -eq 4 ]];
    then
	    echo "bad luck"
    elif [[ $counter -eq 8 ]];
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( counter++ ))
done