#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# At the 4th iteration, it will display "bad luck from China",
# At the 9th iteration, it will display "bad luck from Japan",
# At the 17th, it will display "bad luck from Italy", in place of Best School.

counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        4)
            echo "bad luck from China"
        ;;
        9)
            echo "bad luck from Japan"
        ;;
        17)
            echo "bad luck from Italy"
        ;;
    esac
    (( counter++ ))
done