#!/usr/bin/env bash
# This script displays information about the school file.

file="holbertonschool"

if [ ! -e $file ];
then
	echo "$file file does not exist"
else
	echo "$file file exists"

	if [ ! -s $file ];
	then
		echo "$file file is empty"
	else
		echo "$file file is not empty"
	fi

	if [ -f $file ];
	then
		echo "holbertonschool is a regular file"
	fi
fi